### ISSUE TITLE
Add GTM container code to WP

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#102]
https://docs.google.com/document/d/1EfX9le5EQKyZJLJlvljf-smHxjlbATr6XiJh87bd_Xg/edit?usp=sharing

**Comment by DeniseColbert** [comment]
Unassigned @dhousman as needs to be done in backend

**Comment by johnshaw1000** [comment]
Google Tag Manager set up.

Installed Google Site Kit https://sitekit.withgoogle.com/documentation/

**Comment by DeniseColbert** [comment]
Great, thanks @johnshaw1000 . Unassigned you, and put @dhousman on to review.

**Comment by DeniseColbert** [comment]
Matt to look at sitekit and set up

**Comment by dhousman** [comment]
@DeniseColbert I've been working on this and I'm getting some unexpected results while trying to set things up. Is someone else editing the GA / GTM implementation on this site right now? Who set up the GTAG implementation on that site?

**Comment by DeniseColbert** [comment]
Nobody, other than you, should be touching GTM on Wordpress now the container code is added-  @johnshaw1000 added the container code, but wouldn't have done anything else (he doesn't have access to analytics or GTM).

**Comment by johnshaw1000** [comment]
Apparently some permissions weren't granted, I've done that now.

It's saying it's not connected to analytics - should it be? It prompts to create an account - should I create it or is there an existing one I should use?

**Comment by DeniseColbert** [comment]
@dhousman is trying to get it all set up but there were some issues. @johnshaw1000 could you describe how you added the container code e.g. via a plugin?

**Comment by johnshaw1000** [comment]
Yes, it's just a WordPress plugin called SiteKit by Google. Can @dhousman describe the problem symptoms?

**Comment by DeniseColbert** [comment]
Issues have now been fixed: closing
