### ISSUE TITLE
Configure Yoast

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#104]

**Comment by ghost** [comment]
I installed Yoast and tested it out. Now, I need to work with the SEO person to do a little configuration.

**Comment by MattHFreeUKGen** [comment]
Happy to speak about it from an SEO perspective. 

Send me an email about when works best for you if you want a chat! If not, feel free to let me know what sort of info you need and I can pull something together.

**Comment by DeniseColbert** [comment]
Great to see you here @MattHFreeUKGen !

Gloria is in USA (Chicago time) but I will email you both to arrange a time that suits :)

**Comment by ghost** [comment]
@MattHFreeUKGen and @DeniseColbert - do I close this, now? We have just basic configuration but I think Matt would make changes as he needs more links and features.

**Comment by DeniseColbert** [comment]
Yes, closing
