### ISSUE TITLE
Help page (parent of Contact)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#133]
Is the content on Genealogy Research page sufficient for the Help parent page? Or should this be a child of Help too? @AKHILP96 could we talk about this?

**Comment by akhilpokle** [comment]
I didn't design a help page, I will need clarifications from your side about its contents and it's purpose.

**Comment by DeniseColbert** [comment]
Yes, let's discuss tomorrow at the Meet. The purpose is to hold dropdown for Genealogy Research (parent of potentially many pages), useful links and Contact page.

**Comment by DeniseColbert** [comment]
@TazHinkle will Add Genealogy Research page as a child of Help (on hover) but will review with @AKHILP96 the merits of having a Help page with content vs. a dummy to hold the child pages (on hover)

**Comment by TazHinkle** [comment]
Genealogy Research is now a child of Help- and also the default landing page if someone clicks directly on 'Help' instead of the sub menu.

**Comment by DeniseColbert** [comment]
Done, closing
