### ISSUE TITLE
Place side-menu in Genealogy Research section

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#136]
Is this possible with Elementor? If not, could we easily do it in WP?

**Comment by DeniseColbert** [comment]
@kwheeler08 please take a look at the sidebar

**Comment by johnshaw1000** [comment]
This looks to be "done". I think there's a template created by @kwheeler08 too, which can be used as a base for other sections too.

**Comment by kjawheeler** [comment]
I created two templates, one for Genealogy research and one for open data. They have the original content, but I mainly created them as it saved time creating all the links in the menu.

**Comment by DeniseColbert** [comment]
I think this is done; thanks everyone! Closing
