### ISSUE TITLE
Implement design of Donate feature

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#139]
Pathway that design is based on: https://docs.google.com/drawings/d/1z6OXZ0mHaC2OLcwTTn-myvWCEg2NozaKYTHMWxIbe3w/edit

Code for PayPal buttons & KindLink widget: https://docs.google.com/document/d/1NsScCngGPd66vcNCGIQkcnp9Y_VE4LyNlqSjwf62Yz4/edit#heading=h.187lduc6og1e

**Comment by TazHinkle** [comment]
A current draft of the page exists here:  [https://wp1.freeukgen.org.uk/donation2](https://wp1.freeukgen.org.uk/donation2).
I've added Denise Colbert as a collaborator for the google form which is set up for the Giftaid information.

**Comment by DeniseColbert** [comment]
We have recently discovered another donation pathway - CAFDonate (more info here: https://github.com/freeukgen/coordination/issues/1482)

Could this be added into the widget? @TazHinkle
