### ISSUE TITLE
Create a 'post' as last on news that links to the old website

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#14]

**Comment by johnshaw1000** [comment]
All posts have been moved so not required?

When WP becomes the _current_ site, what will be the address for the _old_ site?

**Comment by DeniseColbert** [comment]
Yes: not required thanks to your solution, John.

Name of old site when WP is live I don't think we have thought about. @lemon-ukgen would it be freeukgenealogy1@freeukgenealogy.org.uk following the REG and CEN pattern?
