### ISSUE TITLE
Open Data section

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#146]

**Comment by johnshaw1000** [comment]
@kwheeler08 I'm happy to help with some of the basic work in this section if you wish. Should I create the placeholder pages and the sidebar?

**Comment by kjawheeler** [comment]
The open data pages have been transferred already, and have a sidebar linking all the pages.

**Comment by kjawheeler** [comment]
https://wp1.freeukgen.org.uk/our-story/open-data

**Comment by DeniseColbert** [comment]
@TazHinkle could you place https://wp1.freeukgen.org.uk/our-story/open-data as a child of Our Story on Nav Bar (dropdown hover)?

**Comment by DeniseColbert** [comment]
Done, closing!
