### ISSUE TITLE
Google Analytics: Account Settings Action Required

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKGenealogyWP#2]
![190625-analytics_action_required.png](https://images.zenhubusercontent.com/5cfdea3834d3c654e1e71985/59521a46-a234-4957-b739-a9eae5c66e04)

Google Analytics reports action required (acceptance of T&CoS update apparently) by admin.

**Comment by ghost** [comment]
@DeniseColbert Assigning this one to you for review/completion.

**Comment by DeniseColbert** [comment]
@PatReynolds could you review these changes to analytics T&Cs re GDPR?

**Comment by DeniseColbert** [comment]
@PatReynolds any update for this?

**Comment by DeniseColbert** [comment]
Seems to no longer be a problem: closing
