### ISSUE TITLE
Add gift aid logo

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#3]
http://www.stmaryscatholicchurchstudley.org.uk/giftAid.html could be used for inspiration.

**Comment by DeniseColbert** [comment]
http://www.glscountyscouts.org.uk/support/gsl/executive/gift/giftaidtoolkit.pdf 

looking for an up to date version...

**Comment by DeniseColbert** [comment]
There doesn't seem to be one!

**Comment by PatReynolds** [comment]
hI don't think the logo/design essentioals have changed.  The governent set up the organization that made this guide, and the design is still used, but the organization folded some time ago - see the 'Gift aid it' section at the bottom of this wikipedia article https://en.wikipedia.org/wiki/Gift_Aid

**Comment by DeniseColbert** [comment]
Duplicate - closing
