### ISSUE TITLE
Move the Contact FAQ and form to the Contact Page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#44]

**Comment by carcarvroom** [comment]
Moved FAQs to Contact Page. 

Created a contact form and tested it with personal email and it is working. These forms will be sent to the admin email (wpsite@turnkeywp.com), please let me know if you would like it sent elsewhere.

**Comment by DeniseColbert** [comment]
Thanks, @carcarvroom! I don't know where emails to wpsite@turnkeywp.com end up but we need them to go to info@freeukgenealogy.org.uk

**Comment by carcarvroom** [comment]
Okay, the email has been updated! I sent a test. Let me know if info@freeukgenealogy.org.uk received it!

**Comment by DeniseColbert** [comment]
I did, thanks! It appeared to come from info@freeukgenealogy.org.uk though, which my email client didn't like:

![image](https://user-images.githubusercontent.com/19173257/98012430-fd106a00-1df0-11eb-9edb-9a762252296b.png)

**Comment by carcarvroom** [comment]
Okay I changed the "email from" address which will be the WP admin email address. I've sent a second test email. 

Could you try replying to the email? It should automatically populate whatever the user enters as the email field, in this case it should be "carly.la@freeukgenealogy.org.uk". Thanks!

**Comment by DeniseColbert** [comment]
Second test didn't arrive @carcarvroom ...

**Comment by carcarvroom** [comment]
Test 3 sent!

**Comment by DeniseColbert** [comment]
Received, thanks :) I hit reply but it didn't populate your email:

![image](https://user-images.githubusercontent.com/19173257/98354013-0fb8b800-2018-11eb-88a4-4fc2b821e560.png)

**Comment by carcarvroom** [comment]
I've sent a test 4. When you reply, the email should populate from the email field this time!

**Comment by DeniseColbert** [comment]
Received twice, both populated with your email address:

![image](https://user-images.githubusercontent.com/19173257/99397316-cd765d00-28da-11eb-9d92-5dafb96eaee2.png)

So, success!
