### ISSUE TITLE
Create teal box on header/bar 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#47]
Done on Akhil's new design.

**Comment by DeniseColbert** [comment]
Re-opening as this hasn't yet been implemented

**Comment by TazHinkle** [comment]
There is a now teal box around Donate in the menu now.  It is a larger size than the design because that is the current size of the clickable button. Moving to Review/QA.

**Comment by DeniseColbert** [comment]
Gloria to take a look at making the Donate button look like the Figma design

**Comment by ghost** [comment]
@denise and @TazHinkle Here is what I did. To me, it looks about the same but the designers will have a finer eye. So, here is what I did and you can adjust it more if they need it. After a change, I hit "Publish" just as a reminder.

**_To change the Top Menu font (Denise, was this part of this ticket or something separate you needed?)_**
Appearance>Customize>Typography>Main Menu>Font Weight
I changed this from Normal:400 to Bold:700.

**_Rounded "Donate" Corners_**
Appearance>Customize>Additional CSS
You can see that I added this:
border-radius: 15px;

**_Shortened the Button_**
"Donate" was too tall. I did two things. First, I shortened it:
Appearance>Customize>Header>General
Set Height (px) to 60

Then, to keep the distance between the menu and the next panel as far away as it was, I went down to Padding (px) and set Bottom to 20.

**Comment by TazHinkle** [comment]
I like this compromise.  I brought up that to make the button smaller that you'd also lose clickable area, but the amount you've trimmed it to is not so small and it looks nicer than the block I had before.

**Comment by DeniseColbert** [comment]
Looks great @hotbeverage2017 ! 

One small thing now though, there is no padding/white space at the top of the nav bar:

![image](https://user-images.githubusercontent.com/19173257/106473795-2007f400-649c-11eb-873e-7fb216473d5c.png)

Is it possible to add some in? [ETA] The same amount as is below the logo/ donate box

**Comment by ghost** [comment]
@TazHinkle @DeniseColbert Feel free to make any changes. If the button seems a little awkward to click on, go ahead and change the area. As for the top, where the other padding was at, where I padded the bottom of the menu bar, I'm pretty sure that also had a top padding, so give that a try and see if you like the way it looks.

The bottom line is this, and I did say this to Denise: I'm a programmer not a UX person. The colors, fonts, etc... will pretty much always look fine to me. So, I'm just looking for "how" to do this not whether it looks just like the example. In my job, I get things to work and someone else makes them look nice. I'm not trying to sound unhelpful when I tell you to go ahead and change it but, seriously, having me do it won't get you closer very fast.

**Comment by DeniseColbert** [comment]
Definitely; it's also good experience for me to do these things myself. I followed your steps and it was really easy to add some top padding- thanks!

All done, closing.

**Comment by TazHinkle** [comment]
The font color now changes to teal on the donate button at hover.  I've also gotten rid of the 'extra underline' on all of the buttons.
