### ISSUE TITLE
Add big teal numbers to statistics in Donate page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogyWP#49]
Done in Akhiil's new design

**Comment by TazHinkle** [comment]
Carly seems to have implemented this already, unless there are a different set of statistics that should be displaying than the 10 pounds per month/30 per day/60 per week..?

**Comment by DeniseColbert** [comment]
Thanks Taz, moving to needs review

**Comment by DeniseColbert** [comment]
Done: closing
