### ISSUE TITLE
Review paid plugins and source free (ideally) replacements

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#60]
Currently in 48in48 build:

- Beaver Builder Pro (Theme and the Themer plugin is included)
https://www.wpbeaverbuilder.com/pricing/ - $199
**Page builder and theme template**

- Ultimate Addons for Beaver Builder
https://www.ultimatebeaver.com/pricing/- $69
**As above**

**We don't need these, but they do make building the website much easier than creating the code from scratch. It would be a bonus to create some of the trickier features (twisties etc.) before we move away from this plugin**

- Gravity Forms (you'll need the Pro license)
https://www.gravityforms.com/add-ons/- $159
**We don't need this but we will need something to replace it. Many free versions out there, but they are basic. Would any suit our needs?**

**Comment by DeniseColbert** [comment]
Updated list of paid-for plugins:

Beaver Builder Plugin (Pro Version) - $199 (lifetime?)
Facebook Feed Add - $27 (lifetime?)
Give - Donation - $199 (annual)
Gravity Forms - $159 (annual)
PowerPack for Beaver Builder - $69 (annual) / $249 (lifetime)
Ultimate Addons for Beaver Builder - $55 (annual) / $249 (lifetime)
WP Feedback Pro - $84 (annual)

**Comment by carcarvroom** [comment]
Deactivated all paid plugins. Currently rebuilding/testing with the following plugins:
Elementor (site builder) - Free
Elementor Essential Add-ons - Free
UpdraftPlus (site/database backups) - Free

Then, looking for free alternatives or will create custom replacements for:
Contact Form
Donations
Facebook Feed

**Comment by DeniseColbert** [comment]
We likely won't need anything on the scale of GiveWP for Donations, we have code for a widget from KindLink, and PayPal buttons. For info, here is the brief for the design of the GBP donations pathway that Akhil is working on: https://docs.google.com/drawings/d/1z6OXZ0mHaC2OLcwTTn-myvWCEg2NozaKYTHMWxIbe3w/edit?usp=sharing

**Comment by DeniseColbert** [comment]
@carcarvroom what do you think of Elementor so far?

**Comment by carcarvroom** [comment]
I think Elementor is the best replacement for Beaver Builder! It's intuitive and really easy to use. I've set global colors and fonts so through Elementor, you don't have to enter the hex colors or fonts manually. 

I have not needed _any_ paid plugins as well!

**Comment by DeniseColbert** [comment]
Looking forward to seeing it in action tomorrow!

**Comment by DeniseColbert** [comment]
Decided to use Elementor to create the website in the quickest way. Once MVP is passed we can replace widgets with our own creations.
