### ISSUE TITLE
Home page collage has repeated image

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#71]
Right-most image of the two to be replaced.

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/eb35c5f8-9ff5-4345-b471-95469d0bd040)

**Comment by akhilpokle** [comment]
[
![collage](https://user-images.githubusercontent.com/17247801/96277521-ffea1d00-0ff1-11eb-8525-d810e398a4bf.png)
](url)

**Comment by DeniseColbert** [comment]
Great, thank you @AKHILP96. Could you add this to the Media subfolder of the Design folder I shared with you earlier?

**Comment by DeniseColbert** [comment]
Appears fixed, closing
