### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by carcarvroom** [FreeUKGen/FreeUKGenealogyWP#84]
@DeniseColbert Could you confirm if these are all the correct media links (I realized I've been using the US links, I'm assuming these should have the .uk domain)? Also, do we want all of these displayed on the site or some omitted?

Facebook - https://www.facebook.com/freeukgen/ 
Instagram - https://www.instagram.com/freeukgenealogy/
Twitter - https://twitter.com/freeukgen?lang=en
Youtube - https://www.youtube.com/c/FreeukgenealogyOrgUkCIO/featured
GIthub - https://github.com/FreeUKGen

**Comment by DeniseColbert** [comment]
Links as below: (Don't think the domain country matters too much but mostly we use .com)

Facebook - https://www.facebook.com/freeukgen/
Twitter - https://twitter.com/freeukgen/
Instagram - https://www.instagram.com/freeukgenealogy/
Pinterest - https://www.pinterest.co.uk/FreeUKGenealogy
YouTube - https://www.youtube.com/c/FreeukgenealogyOrgUkCIO/
GitHub - https://github.com/FreeUKGen

**(Taken from https://www.freeukgenealogy.org.uk/about/pages/other-ways-to-help/social-community/)**

> Also, do we want all of these displayed on the site or some omitted?

Hmmm. Depends. I think we want all of them in the footer (see https://jayto581.github.io/FUG_Demo/ for the design for the footer in our other websites - we will add GH & YT) but where else are you thinking for them to be placed @carcarvroom ?

**Comment by carcarvroom** [comment]
Thank you for the links! I think keeping all the media links in the footer would be best!
