### ISSUE TITLE
Investigate migrating news posts from Craft to WP

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#89]
As detailed in https://kickpoint.ca/migrating-posts-from-craft-cms-to-wordpress/ (the tool they mention is https://github.com/paper-leaf/commandervee)

**Comment by johnshaw1000** [comment]
Web crawler results added to https://docs.google.com/spreadsheets/d/1v_eVzItwVksdpZ62GKhf-5sPhO9Jk7OdErtajcP1g34/edit?usp=sharing

**Comment by DeniseColbert** [comment]
Thanks @johnshaw1000 .

**Comment by johnshaw1000** [comment]
The migration script has been added to GitHub. I haven't added any of the files I've used but I can do if desired. These files are:

- source HTML downloaded from the current site
- target posts HTML for upload to the WP site
- image files

Additionally a couple of other media files were copied from the current to the WP site manually (PDF and MP4).
