### ISSUE TITLE
Add Museo font to WordPress

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#90]
There are three weights [available here](https://www.fontsquirrel.com/fonts/museo) for free. We want 300 for Reg & 500 for Bold.

**Comment by DeniseColbert** [comment]
I had a look at adding this through Elementor and it doesn't seem possible. Is it possible through WP? Or PHP?

**Comment by akhilpokle** [comment]
Are we planning on using it?

**Comment by DeniseColbert** [comment]
Yes @AKHILP96 we want to use this font for quotes on the website, e.g. testimonial carousel

**Comment by johnshaw1000** [comment]
![Screenshot 2021-01-29 at 20 18 27](https://user-images.githubusercontent.com/5745442/106323365-3bda8280-626f-11eb-9dab-0b031b28fe88.png)
Need to "Go Pro" with Elementor to be able to add custom fonts. There might be another way, I'll keep looking.

**Comment by DeniseColbert** [comment]
Thanks @johnshaw1000 

*crosses fingers*

**Comment by johnshaw1000** [comment]
Fonts added to Wordpress site.
README.md file updated in GitHub repo to describe changes and to refer to fonts license.
Font assets uploaded to GitHub repo.

**Comment by johnshaw1000** [comment]
The "testimonial" or "testimonial-bold" CSS class must be entered in the advanced section of the testimonial widget (or anywhere really, but I assumed it was limited to testimonials).
![Screenshot 2021-02-24 at 20 52 38](https://user-images.githubusercontent.com/5745442/109064857-d00afe80-76e2-11eb-8b57-02efad580c2a.png)

**Comment by DeniseColbert** [comment]
The Museo font is only to be used for quotes, so testimonial widget is the only place it's used currently, but it may be used elsewhere on the site. Maybe 'quote' would be a more suitable name for the class?
