### ISSUE TITLE
Review Document of Qs we want analytics to answer

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogyWP#91]
https://docs.google.com/document/d/1bzMacIa0wAweMMl-OioA-EyCqqqflnALATdEaxNMrg8/edit?usp=sharing

Make stories for tasks required in WP.

**Comment by dhousman** [comment]
@DeniseColbert can you provide some mocks of the new wordpress fukg site? Or access to the site itself?

**Comment by DeniseColbert** [comment]
@dhousman I saw a comment on this story from you in my emails but can't see it in GitHub, Oh well... I have given you access to WP

**Comment by dhousman** [comment]
I think this has been done and questions are now found here: https://docs.google.com/document/d/1_iGnBQOhvmhlILIsbCAvJ2zSbBs1uQvEc6JSoCsHAUg/edit

**Comment by DeniseColbert** [comment]
@dhousman are all stories coming out of this document now on the board? I will close, if so.

**Comment by dhousman** [comment]
Yes i think so please close
